# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_Draw' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Test_Draw

   pod 'Masonry', '~> 1.1.0'


  target 'Test_DrawUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
