# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC_Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RAC_Test
  #pod 'ReactiveCocoa', '~> 8.0.0-rc.1'
  pod 'ReactiveObjC', '~> 3.1.0'

  target 'RAC_TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC_TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
